s = set()
n = input("Enter the numer 1: ")
s.add(int(n))
n = input("Enter the numer 1: ")
s.add(int(n))
n = input("Enter the numer 1: ")
s.add(int(n))
n = input("Enter the numer 1: ")
s.add(int(n))
n = input("Enter the numer 1: ")
s.add(int(n))
n = input("Enter the numer 1: ")
s.add(int(n))
n = input("Enter the numer 1: ")
s.add(int(n))
n = input("Enter the numer 1: ")
s.add(int(n))

print(s)